### ISSUE TITLE
Bulk generation

### ISSUE THREAD

**Issue by idalarsson** [KevinMenden/scaden#36] opened 2020-10-08 10:51 UTC
Hi, 

I was wondering how I obtain the scripts for generating bulk from my single cell data (bulk_generation.py)?

Best,
Ida

**Comment by KevinMenden** [comment] 2020-10-08 11:01
Hi Ida,

just have a look in the scaden/preprocessing directory in this repo.

They are unfortunately not yet included in the main tool, sorry for that.

Bw,
Kevin

**Comment by KevinMenden** [comment] 2020-10-08 11:05
@idalarsson a quick follow up, because a different user had an issue:

you may want to use the scripts from the 'dev' branch, which has not been merged in the master branch yet.
the scripts from the main branch can lead to dependency issues with pandas.

Let me know if you encounter any problems!

**Comment by idalarsson** [comment] 2020-10-08 12:06
Thank you! :)

**Comment by idalarsson** [comment] 2020-10-12 13:04
Hello again,

I've now managed to get bulk_generation.py to work in my data, but encounter an error when trying to create the h5ad-file. The error message is:

```
Celltypes: [1, 2, 3, 4, 5, 6]
Traceback (most recent call last):
  File "create_h5ad_file.py", line 98, in <module>
    y = sort_celltypes(y, labels, celltypes)
  File "create_h5ad_file.py", line 55, in sort_celltypes
    idx = [labels.index(x) for x in ref_labels]
  File "create_h5ad_file.py", line 55, in <listcomp>
    idx = [labels.index(x) for x in ref_labels]
ValueError: 1 is not in list
```
Does this tell you anything?

**Comment by nicolasgoedert97** [comment] 2021-01-14 16:44
I'm receiving the same type of error as @idalarsson. Did you solve the problem?

**Comment by KevinMenden** [comment] 2021-01-14 16:58
Ah @idalarsson sorry for not reaching out again I didn't get any notification apparently because the issue is closed :/ 

@nicolasgoedert97 Have you tried running Scaden with the example data that can be generated?
Did you check that the format fits?

This seems like to be a formatting issue leading to Scaden not being able to parse the celltypes correctly.
Let me know if all of that works and if the format looked good!

I'm reopening this so I'm sure to be notifiede.

**Comment by nicolasgoedert97** [comment] 2021-01-23 16:14
@KevinMenden yup It was a formatting error for me. Applying the same format as in example data solved the issue.

**Comment by KevinMenden** [comment] 2021-01-23 16:31
Perfect, glad to hear that 👍

**Closed by KevinMenden** 2021-01-23 16:31 UTC
